name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build PDF
      uses: docker://vvakame/review:3.1
      with:
        args: ./buildPdf.sh
    - uses: actions/upload-artifact@master
      with:
        name: artifact
        path: articles/ReVIEW-Template.pdf
